application: jackqian2012-1 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /.*
  script: helloworld.app

